pull_request_rules:
  - name: self-assign PRs
    conditions:
      - -merged
      - -closed
      - "#assignee=0"
    actions:
      assign:
        add_users:
          - "{{ author }}"
  - name: automatic merge
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=test-python (3.10)
      - check-success=test-nix
      - check-success=test-bazel
      - label!=work-in-progress
    actions:
      queue:
        name: default
queue_rules:
  - name: default
    merge_method: fast-forward
    update_method: rebase
    update_bot_account: pyrovelocity-bot
    merge_bot_account: pyrovelocity-bot
    conditions:
      - check-success=test-python (3.10)
      - check-success=test-nix
      - check-success=test-bazel
