pull_request_rules:
  - name: self-assign PRs
    conditions:
      - -merged
      - -closed
      - "#assignee=0"
    actions:
      assign:
        add_users:
          - "{{ author }}"
  - name: automatic merge when not WIP, CI passes, and at least 1 approving review
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=test-python (3.10)
      - check-success=test-nix
      - check-success=test-bazel
      - label!=work-in-progress
    actions:
      queue:
        method: fast-forward
        name: default
queue_rules:
  - name: default
    conditions:
      - check-success=test-python (3.10)
      - check-success=test-nix
      - check-success=test-bazel
