exclude: |
  (?x)^(
    conda/recipe/meta.yaml|
    conda/conda-lock.yml|
    reproducibility/figures/models/.*|
    reproducibility/figures/config.yaml|
    dev
  )$
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--target-version, py37, --line-length, "80"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py3-plus, --py38-plus, --keep-runtime-typing]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.7
  - repo: local
    hooks:
      - id: set-git-env
        name: Set git ref and rev to environment variables
        entry: ./scripts/git/set-git-env.sh
        language: script
        stages: [post-checkout, post-commit, manual]
      - id: nix-fmt
        name: Format nix flake
        entry: ./scripts/nixfmt
        language: script
      - id: cue-fmt
        name: Format CUE modules
        entry: ./scripts/cuefmt
        language: script
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: false
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
