version: "3"
name: pyrovelocity
services:
  jupyter:
    image: "${DEVCONTAINER_IMAGE:-ghcr.io/pinellolab/pyrovelocitydev:main}"
    command: jupyter lab --allow-root --ip=0.0.0.0 /root/pyrovelocity
    ports:
      - "8888:8888"
    tty: true
    stdin_open: true
    restart: "no"
    volumes:
      - ${PWD}:/root/pyrovelocity
