name: "Setup Environment"
description: "Shared steps to setup the environment for CI jobs"

inputs:
  python_version:
    description: "Python version to setup"
    required: true
  debug_enabled:
    description: "Run with tmate.io debugging enabled"
    required: true
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # ratchet:actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install system dependencies
      shell: bash
      run: |
        echo "install system dependencies"
        # sudo apt-get update
        # sudo apt-get install -y tree
    - uses: r-lib/actions/setup-pandoc@0ed4cdf40958ef43a6b33b9792e07ac76c3239e3 # ratchet:r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: "3.1.11"
    - name: Install Poetry
      uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b # ratchet:snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      shell: bash
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --with docs,lint,test,workflows --no-interaction --no-root
    - name: Install project
      shell: bash
      run: poetry install --with docs,lint,test,workflows --no-interaction
    - name: "Setup tmate debug session"
      uses: mxschmitt/action-tmate@a283f9441d2d96eb62436dc46d7014f5d357ac22 # ratchet:mxschmitt/action-tmate@v3
      if: ${{ inputs.debug_enabled == 'true' }}
