name: "Build Nix Docker Image"
description: "Builds a Docker image using Nix"
inputs:
  triggerEventName:
    description: "The name of the event that triggered the workflow"
    required: true
  imageName:
    description: "Name of the Docker image"
    required: true
  imageFQN:
    description: "Fully Qualified Name of the Docker image"
    required: true
  nixCommand:
    description: "Nix command to build the image"
    required: true
  gcpProjectId:
    description: "Google Cloud Project ID"
    required: true
  encodedGARCredentials:
    description: "Base64 encoded Google Artifact Registry Service Account credentials"
    required: true
  # cachixCacheName:
  #   description: "Name of the Cachix cache"
  #   required: false
  # cachixAuthToken:
  #   description: "Cachix authentication token"
  #   required: false

runs:
  using: "composite"
  steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # ratchet:docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Install Skopeo
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -yq skopeo
        sudo apt-get clean

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@e279ba56d8266c08a0e65738145aabb824f308ed # ratchet:DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          extra-platforms = aarch64-linux

    - name: Setup Local Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@eeabdb06718ac63a7021c6132129679a8e22d0c7 # ratchet:DeterminateSystems/magic-nix-cache-action@v3

    # - name: Setup Remote Nix Cache
    #   uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # ratchet:cachix/cachix-action@v14
    #   with:
    #     name: "${{ inputs.cachixCacheName }}"
    #     authToken: "${{ inputs.cachixAuthToken }}"

    - name: Set GitHub CI Slug Variables
      uses: rlespinasse/github-slug-action@102b1a064a9b145e56556e22b18b19c624538d94 # ratchet:rlespinasse/github-slug-action@v4
      with:
        prefix: CI_

    - name: Set git variables
      shell: bash
      run: |
        echo "GIT_REPO_NAME=$CI_GITHUB_REPOSITORY_NAME_PART" >> $GITHUB_ENV
        echo "GIT_REF=$CI_GITHUB_REF_NAME" >> $GITHUB_ENV
        if [ "${{ inputs.triggerEventName }}" == "pull_request" ]; then
          echo "GIT_SHA=$CI_GITHUB_EVENT_PULL_REQUEST_HEAD_SHA" >> $GITHUB_ENV
          echo "GIT_SHA_SHORT=$CI_GITHUB_EVENT_PULL_REQUEST_HEAD_SHA_SHORT" >> $GITHUB_ENV
        else
          echo "GIT_SHA=$CI_GITHUB_SHA" >> $GITHUB_ENV
          echo "GIT_SHA_SHORT=$CI_GITHUB_SHA_SHORT" >> $GITHUB_ENV
        fi

    - name: Set nix variables
      shell: bash
      run: |
        echo "NIX_IMAGE_SYSTEMS=x86_64-linux" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      shell: bash
      run: |
        set -euxo pipefail

        echo "Using Git Repository Name: $GIT_REPO_NAME"
        echo "Using Git Reference: $GIT_REF"
        echo "Using Git SHA: $GIT_SHA"
        echo "Using Git SHA Short: $GIT_SHA_SHORT"
        FQN_GIT_SHA="${{ inputs.imageFQN }}:$GIT_SHA"
        echo "Image FQN with Git SHA: $FQN_GIT_SHA"
        df -h
        if SKOPEO_OUTPUT=$(skopeo inspect "docker://$FQN_GIT_SHA" 2>&1); then
          echo "Image $FQN_GIT_SHA already exists. Skipping build."
        else
          if echo "$SKOPEO_OUTPUT" | grep -q 'manifest unknown'; then
            echo "Image $FQN_GIT_SHA does not exist. Building."
            ${{ inputs.nixCommand }}
          else
            echo "Failed to inspect image with error: $SKOPEO_OUTPUT"
            exit 1
          fi
        fi
        df -h
      env:
        GH_TOKEN: ${{ github.token }}
        GCP_PROJECT_ID: ${{ inputs.gcpProjectId }}
        ENCODED_GAR_SA_CREDS: ${{ inputs.encodedGARCredentials }}
