project:
  type: website
  output-dir: _site

execute:
  warning: false
  error: false

back-to-top-navigation: true

website:
  title: "Pyro-Velocity"
  site-url: https://pinellolab.github.io/pyrovelocity
  description: "A probabilistic framework for multi-modal transcriptomics"
  favicon: _static/logo/favicon.ico

  page-footer:
    border: false
    left: ""
    right:
      - icon: github
        href: https://github.com/pinellolab/pyrovelocity

  search:
    type: overlay

  navbar:
    background: primary
    logo: _static/logo.png
    tools:
      - icon: github
        menu:
          - text: "Repository"
            url: https://github.com/pinellolab/pyrovelocity
          - text: "Start a discussion"
            url: https://github.com/pinellolab/pyrovelocity/discussions/new/choose
          - text: "Create an issue"
            url: https://github.com/pinellolab/pyrovelocity/issues/new/choose

  sidebar:
    style: "floating"
    contents:
      - text: "Introduction"
        href: introduction.qmd
      - section: "Concepts"
        contents:
          - text: "Overview"
            href: concepts/overview.qmd
          - text: "Multi-modal transcriptomics"
            href: concepts/multimodaltranscriptomics.qmd
          - text: "Dynamical systems theory"
            href: concepts/dynamicalsystems.qmd
          - text: "Probabilistic inference"
            href: concepts/probabilisticinference.qmd
          - text: "Models of gene expression"
            href: concepts/geneexpression.qmd
      - section: "Guides"
        contents:
          - text: "Data Access"
            href: guides/data.qmd
          - text: "Preprocessing"
            href: guides/preprocessing.qmd
          - text: "Inference"
            href: guides/inference.qmd
          - text: "Postprocessing"
            href: guides/postprocessing.qmd
          - text: "Model summary"
            href: guides/summarization.qmd
      - section: "Tutorials"
        contents:
          - section: "Analysis templates"
            contents:
              - text: "PyPI"
                href: templates/pypi.qmd
              - text: "Conda"
                href: templates/conda.qmd
          - text: "Pancreatic endocrinogenesis"
            href: tutorials/pancreas.qmd
          - text: "Pons development"
            href: tutorials/pons.qmd
          - section: "Blood physiology"
            contents:
              - text: "68k PBMCs"
                href: tutorials/pbmc68k.qmd
              - text: "10k PBMCs"
                href: tutorials/pbmc10k.qmd
              - text: "5k PBMCs"
                href: tutorials/pbmc5k.qmd
          - text: "Mouse hematopoiesis"
            href: tutorials/mousehematopoiesis.qmd
          - text: "Lineage tracing"
            href: tutorials/lineagetracing.qmd
      - section: "Reference"
        contents:
          - text: "Models"
            href: reference/models.qmd
          - text: "Plots"
            href: reference/plots.qmd
          - text: "Tasks"
            href: reference/tasks.qmd
          - text: "Workflows"
            href: reference/workflows.qmd
      - section: "About"
        contents:
          - text: "Changelog"
            href: about/changelog.qmd
          - text: "Contributing"
            href: about/contributing.qmd
          - text: "Credits"
            href: about/credits.qmd

format:
  html:
    theme:
      light: [flatly, clight.scss]
      dark: [darkly, cdark.scss]
    include-in-header: include.html
    css: styles.css
    toc: true
