name: CML Images

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - "containers/**"
  #     - "pyrovelocity/**"
  #     - "pyproject.toml"
  #     - "poetry.lock"
  #   branches:
  #     - 'main*'

env:
  REGISTRY: ghcr.io
  GAR_REGISTRY: us-central1-docker.pkg.dev
  GAR_REPOSITORY: pyrovelocity
  IMAGE_NAME: ${{ github.repository }}-cml
  CONDA_IMAGE_NAME: ${{ github.repository }}-conda-gpu

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Print github context"
        run: |
          echo "      EVENT_NAME:" "$GITHUB_EVENT_NAME"
          echo "             REF:" "$GITHUB_REF"
          echo "       full_name: ${{ github.event.repository.full_name }}"
          echo "      repository: ${{ github.repository }}"
          echo "repository_owner: ${{ github.repository_owner }}"
          echo "  default_branch: ${{ github.event.repository.default_branch }}"
          echo "REPOSITORY_OWNER:" "$GITHUB_REPOSITORY_OWNER"
          echo "        REF_NAME:" "$GITHUB_REF_NAME"
          echo "        HEAD_REF:" "$GITHUB_HEAD_REF"
          echo "        BASE_REF:" "$GITHUB_BASE_REF"
          echo "             SHA:" "$GITHUB_SHA"
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # ratchet:docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # ratchet:docker/setup-buildx-action@v2
        # with:
        #   driver-opts: |
        #     image=moby/buildkit:v0.10.6
      - name: Log in to container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract github metadata for docker labels
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: ./containers/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-conda-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Print github context"
        run: |
          echo "      EVENT_NAME:" "$GITHUB_EVENT_NAME"
          echo "             REF:" "$GITHUB_REF"
          echo "       full_name: ${{ github.event.repository.full_name }}"
          echo "      repository: ${{ github.repository }}"
          echo "repository_owner: ${{ github.repository_owner }}"
          echo "  default_branch: ${{ github.event.repository.default_branch }}"
          echo "REPOSITORY_OWNER:" "$GITHUB_REPOSITORY_OWNER"
          echo "        REF_NAME:" "$GITHUB_REF_NAME"
          echo "        HEAD_REF:" "$GITHUB_HEAD_REF"
          echo "        BASE_REF:" "$GITHUB_BASE_REF"
          echo "             SHA:" "$GITHUB_SHA"
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # ratchet:docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # ratchet:docker/setup-buildx-action@v2
      - name: Log in to GitHub container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to Google Artifact Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ${{ env.GAR_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
      - name: Extract github metadata for docker labels
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.CONDA_IMAGE_NAME }}
            ${{ env.GAR_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.CONDA_IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=,format=long
      - name: Build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: ./containers/Dockerfile.conda
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
