name: CML

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run the build with tmate debugging enabled (mxschmitt/action-tmate)"
        required: false
        default: "false"
  push:
    branches:
      - "exp*"
    paths:
      - "pyrovelocity/**"
      - "reproducibility/figures/*.py"
      - "reproducibility/figures/dvc.*"
      - "reproducibility/figures/config.yaml"

# review/set variables via gh CLI:
#
#   gh secret list --repo=$(GH_REPO)
#   gh secret set PERSONAL_ACCESS_TOKEN --repo="$(GH_REPO)" --body="$(GH_PAT)"
#
# see also:
#   https://cml.dev/doc/self-hosted-runners?tab=GitHub#personal-access-token
env:
  REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
  TF_LOG_PROVIDER: DEBUG

jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: iterative/setup-cml@v1
      # - name: Setup tmate debug session
      #   uses: mxschmitt/action-tmate@v3
      #   if: ${{ github.event.inputs.debug_enabled }}
      - name: Deploy cloud runner instance
        run: |
          cml runner launch \
          --labels=cml-gpu \
          --reuse-idle \
          --cloud=gcp \
          --cloud-type=n1-standard-16+nvidia-tesla-t4*1 \
          --cloud-hdd-size=300 \
          --cloud-spot \
          --cloud-region=us-central1-c \
          --cloud-permission-set="${GCP_SERVICE_ACCOUNT},scopes=storage-rw"
      # - name: test
      #   run: echo "cml"
