name: CML

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (mxschmitt/action-tmate)'
        required: false
        default: "false"
  push:
    branches:    
      - 'exp*'
    paths:
      - "pyrovelocity/**"
      - "reproducibility/figures/*.py"
      - "reproducibility/figures/dvc.*"
      - "reproducibility/figures/config.yaml"

jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: test
        run: echo "cml"
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event.inputs.debug_enabled }}
